---
- name: viafront
  hosts: all
  become: yes
  become_user: root

  vars:
    dotnet_run_env: "{{ 'export ASPNETCORE_ENVIRONMENT=Development' if DEPLOY_TYPE == 'test' else '' }}"
  tasks:
    - name: ansible group
      group: 
        name: viafront
        state: present

    - name: ansible user
      user:
        name: viafront
        shell: /usr/sbin/nologin
        groups: viafront
        system: yes
        state: present

    - name: copy viafront3.zip
      copy:
        src: ../viafront3.zip
        dest: /opt/viafront3.zip

    - name: extract viafront3.zip
      shell: unzip -o /opt/viafront3.zip -d /opt/viafront

    - name: extract submodule zip files
      shell: cd /opt/viafront; unzip -o '*.zip'

    - name: set viafront files owner
      file:
        dest: /opt/viafront
        owner: viafront
        group: viafront
        mode: 0755
        recurse: yes

    - name: set mysql host for asp.net db
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("DefaultConnection": "Server=)10\.50\.1\.2(;Database)'
        replace: '\1{{backend_host}}\2'

    - name: set mysql host for viaxch db
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("Host": ")10\.50\.1\.2(")'
        replace: '\1{{backend_host}}\2'

    - name: set accesshttp url 
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("AccessHttpUrl": "http:\/\/)10\.50\.1\.2(:8080")'
        replace: '\1{{backend_host}}\2'

    - name: set accessws url
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("AccessWsUrl": "ws:\/\/)10\.50\.1\.2(:8090")'
        replace: '\1{{backend_host}}\2'

    - name: set waves node url
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("WavesNodeUrl": "http:\/\/)localhost(:6869")'
        replace: '\1{{blockchain_host}}\2'

    - name: set nbxexplorer url
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("NbxplorerUrl": "http:\/\/)localhost(:24444")'
        replace: '\1{{blockchain_host}}\2'

    - name: copy viafront.service
      template:
        src: templates/viafront.service
        dest: /etc/systemd/system/viafront.service

    - name: install npm & node
      action: apt pkg={{item}} state=installed
      with_items:
        - nodejs-legacy
        - npm

    - name: install bower
      shell: cd /opt/viafront; npm install bower
      become: yes
      become_user: viafront

    - name: dotnet restore packages 
      shell: cd /opt/viafront; dotnet restore;
      become: yes
      become_user: viafront

    - name: EF migrations
      shell: cd /opt/viafront; dotnet ef database update
      become: yes
      become_user: viafront

    - name: add roles
      shell: cd /opt/viafront; dotnet run console initroles
      become: yes
      become_user: viafront

    - name: init db for wallets
      shell: cd /opt/viafront; export DB_TYPE=sqlite; export CONNECTION_STRING="Data Source={{item}}"; dotnet ef database update --project xchwallet/xchwallet/xchwallet.csproj --context WalletContext
      become: yes
      become_user: viafront
      with_items:
        - waves_wallet.db
        - btc_wallet.db

    - name: stop viafront service
      service: 
        name: viafront
        state: stopped
        enabled: no

    - name: start viafront service
      service: 
        name: viafront
        state: started
        enabled: yes
