---
- name: viafront
  hosts: all
  become: yes
  become_user: root

  vars:
    dotnet_run_env: "{{ 'export ASPNETCORE_ENVIRONMENT=Development' if DEPLOY_TYPE == 'test' else '' }}"
  tasks:
    - name: ansible group
      group: 
        name: viafront
        state: present

    - name: ansible user
      user:
        name: viafront
        shell: /usr/sbin/nologin
        groups: viafront
        system: yes
        state: present

    - name: copy viafront3.zip
      copy:
        src: ../viafront3.zip
        dest: /opt/viafront3.zip

    - name: extract viafront3.zip
      shell: unzip -o /opt/viafront3.zip -d /opt/viafront

    - name: extract submodule zip files
      shell: cd /opt/viafront; unzip -o '*.zip'

    - name: set viafront files owner
      file:
        dest: /opt/viafront
        owner: viafront
        group: viafront
        mode: 0755
        recurse: yes

    - name: set mysql host for asp.net db
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("DefaultConnection": "Server=)localhost(;Database)'
        replace: '\1{{backend_host}}\2'

    - name: set mysql host for viaxch db
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("Host": ")localhost(")'
        replace: '\1{{backend_host}}\2'

    - name: set mysql host for wallets db
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("Host": ")localhost(")'
        replace: '\1{{backend_host}}\2'

    - name: set accesshttp url 
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("AccessHttpUrl": "http:\/\/)localhost(:8080")'
        replace: '\1{{backend_host}}\2'

    - name: set accessws url
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("AccessWsUrl": "ws:\/\/)localhost(:8090")'
        replace: '\1{{backend_host}}\2'

    - name: set accessws ip
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("AccessWsIp": ")127\.0\.0\.1(")'
        replace: '\1{{backend_ip}}\2'

    - name: set websocket url
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("WebsocketUrl": ")ws:\/\/localhost\/ws(")'
        replace: '\1wss:\/\/{{deploy_host}}\/ws\/\2'

    - name: set kafka host
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("KafkaHost": ")127\.0\.0\.1(:9092")'
        replace: '\1{{backend_host}}\2'

    - name: set waves node url
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("NodeUrl": "http:\/\/)localhost(:6869")'
        replace: '\1{{blockchain_host}}\2'

    - name: set zap node url
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("NodeUrl": "http:\/\/)localhost(:6869")'
        replace: '\1{{blockchain_host}}\2'

    - name: set nbxexplorer url
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("NodeUrl": "http:\/\/)localhost(:24444")'
        replace: '\1{{blockchain_host}}\2'

    - name: set from email
      replace:
        path: /opt/viafront/appsettings.json
        regexp: '("From": ")admin@viafront3.com(")'
        replace: '\1{{admin_email}}\2'

    - name: copy viafront.service
      template:
        src: templates/viafront.service
        dest: /etc/systemd/system/viafront.service

    - name: stop viafront service
      service: 
        name: viafront
        state: stopped
        enabled: no

    - name: copy viafront_order_emails.service
      template:
        src: templates/viafront_order_emails.service
        dest: /etc/systemd/system/viafront_order_emails.service

    - name: stop viafront_order_emails service
      service: 
        name: viafront_order_emails
        state: stopped
        enabled: no

    - name: install npm & node
      action: apt pkg={{item}} state=installed
      with_items:
        - nodejs-legacy
        - npm

    - name: install bower
      shell: cd /opt/viafront; npm install bower
      become: yes
      become_user: viafront

    - name: dotnet restore packages 
      shell: cd /opt/viafront; dotnet restore;
      become: yes
      become_user: viafront

    - name: dotnet build
      shell: cd /opt/viafront; dotnet build;
      become: yes
      become_user: viafront

    - name: EF migrations
      shell: cd /opt/viafront; dotnet ef database update
      become: yes
      become_user: viafront

    - name: add roles
      shell: cd /opt/viafront; dotnet run console initroles
      become: yes
      become_user: viafront

    - name: init wallet dbs
      shell: python /opt/viafront/init_wallet_dbs.py /opt/viafront/appsettings.json /opt/viafront/xchwallet/xchwallet/ /opt/viafront
      become: yes
      become_user: viafront

    - name: start viafront service
      service: 
        name: viafront
        state: started
        enabled: yes

    - name: start viafront_order_emails service
      service: 
        name: viafront_order_emails
        state: started
        enabled: yes

    - name: set cron shell
      cron:
        name: SHELL
        env: yes
        value: /bin/bash

    - name: copy the deposit and withdrawal script
      template:
        src: templates/process_deposits_and_withdrawals.sh
        dest: /opt/viafront/process_deposits_and_withdrawals.sh
        mode: 0755

    - name: run the deposit and withdrawal script
      cron:
        name: viafront deposits and withdrawal script
        minute: "*/10"
        job: /opt/viafront/process_deposits_and_withdrawals.sh
